version: '3'

services:

  app:
    build: 
      context: ./node
      dockerfile: Dockerfile
    image: vbardella/node
    container_name: node_app
    tty: true 
    networks:
      - nodenet
    volumes:
      - ./node/app:/usr/src/app

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile 
    image: vbardella/nginx
    tty: true
    container_name: node_nginx
    ports:
      - "8080:80" 
    networks:
      - nodenet

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: node_db
    restart: always
    tty: true
    ports:
      - "3307:3306" 
    volumes:
      - ./mysql/db_data:/var/lib/mysql
      - ./mysql/script:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: node_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha   
    networks:
      - nodenet 

networks:
  nodenet:
    driver: bridge
 